// EURO LOTTO
export const EURO_PRIMARY_NUMBER_RANGE = 50;
export const EURO_SECONDARY_NUMBER_RANGE = 12;

// VIKING LOTTO
export const VIKING_PRIMARY_NUMBER_RANGE = 48;
export const VIKING_SECONDARY_NUMBER_RANGE = 5;

// KENO LOTTO
export const KENO_PRIMARY_NUMBER_RANGE = 64;

// JOKKER LOTTO
export const JOKKER_PRIMARY_NUMBER_RANGE = 9;

// BINGO LOTTO
export const BINGO_PRIMARY_NUMBER_RANGE = 75;
export const BINGO_CENTER_NUMBER_RANGE = 15;
export const BINGO_CORNER_NUMBER_RANGE = 33;
export const BINGO_DIAGONAL_NUMBER_RANGE = 38;
export const BINGO_CENTER_SQUARE_GAME_WIN_CLASS = 5;
export const BINGO_CORNER_SQUARE_GAME_WIN_CLASS = 4;
export const BINGO_DIAGONAL_SQUARE_GAME_WIN_CLASS = 3;
