// EURO LOTTO
export const EURO_PRIMARY_NUMBER_RANGE = {start: 1, end: 50};
export const EURO_SECONDARY_NUMBER_RANGE = {start: 1, end: 12};

// VIKING LOTTO
export const VIKING_PRIMARY_NUMBER_RANGE = {start: 1, end: 48};
export const VIKING_SECONDARY_NUMBER_RANGE = {start: 1, end: 5};

// KENO LOTTO
export const KENO_PRIMARY_NUMBER_RANGE = {start: 1, end: 64};

// JOKKER LOTTO
export const JOKKER_PRIMARY_NUMBER_RANGE = {start: 0, end: 9};

// BINGO LOTTO
export const BINGO_PRIMARY_NUMBER_RANGE = {start: 1, end: 75};
export const BINGO_CENTER_NUMBER_RANGE = {start: 31, end: 45};
export const BINGO_CORNER_NUMBER_RANGE = BINGO_PRIMARY_NUMBER_RANGE;
export const BINGO_DIAGONAL_NUMBER_RANGE = BINGO_PRIMARY_NUMBER_RANGE;
export const BINGO_CENTER_SQUARE_GAME_WIN_CLASS = 5;
export const BINGO_CORNER_SQUARE_GAME_WIN_CLASS = 4;
export const BINGO_DIAGONAL_SQUARE_GAME_WIN_CLASS = 3;
